#!/usr/bin/env python3
import sys
import os  # ✅ เพิ่มตัวนี้
from dotenv import load_dotenv
import asyncio
import datetime
from apiapp.modules.user.model import User
from apiapp.infrastructure.database import init_beanie

load_dotenv()
async def create_user_admin():
    class Setting:
        def __init__(self):
            self.DATABASE_URI = os.getenv(
                "DATABASE_URI", 
                "mongodb://localhost:27017/aquasense"
            )

    settings = Setting()
    
    print(f"Connecting to: {settings.DATABASE_URI}") 
    await init_beanie(settings)

    print("Checking admin user...")
    user = await User.find_one(User.username == "admin")

    if user:
        print(f"Admin already exists: {user.username}")
        return

    print("Creating admin user...")
    user = User(
        email="admin@example.com",
        username="admin",
        hashed_password="",
        name="Administrator",
        role="admin",
        is_active=True,
    )
    user.set_password("p@ssw0rd") 
    await user.save()
    print("Admin created successfully!")

if __name__ == "__main__":
    asyncio.run(create_user_admin())